---
title: "check MEAD"
author: "Dongyue Xie"
date: "2022-11-15"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Setting 2, 3 blocks

```{r}
sigma_all = readRDS('output/check_MEAD/sigma_3blocks.rds')
image(sigma_all[[1]]+sigma_all[[2]]+sigma_all[[3]])
```

### Sandwich with all correlated gene-paires

```{r}
library(vioplot)
Pi_mead_all=sd_all0=array(0,dim=c(3,500,100))
for(seedN in 1:100){
  load(file=paste("output/check_MEAD/MEAD_res_",seedN,".RData",sep=""))
  Pi_mead_all[,,seedN]=MEAD_res$p_hat
  sd_all0[,,seedN]=MEAD_res$p_hat_se
}
Pi = readRDS('output/check_MEAD/Pi.rds')
```


```{r}
alpha=0.975
cp_mead=NULL
for(j in 1:500){
  int_lower=Pi_mead_all[,j,]-qnorm(alpha)*sd_all0[,j,]
  int_upper=Pi_mead_all[,j,]+qnorm(alpha)*sd_all0[,j,]

  tab1=sapply(1:3,function(k){
    sum(sapply(1:100,function(i) sum(Pi[k,j]<int_upper[k,i] & Pi[k,j]>int_lower[k,i]) ))/100
  })


  cp_mead=rbind(cp_mead,tab1)
}
apply(cp_mead,2,median)
#save(cp_mead,file="output/check_MEAD/cp_mead.RData")

colnames(cp_mead)=c("Cell 1","Cell 2","Cell 3")
vioplot(cp_mead,col=c("grey","lightcoral","skyblue"),ylim=c(0.6,1))
lines(c(0.5,3.5),c(0.95,0.95),lty=2)
```

### Sandwich with no correlated gene-pair

```{r}
Pi_mead_all=sd_all0=array(0,dim=c(3,500,100))
for(seedN in 1:100){
  load(file=paste("output/check_MEAD/MEAD_res_noR_",seedN,".RData",sep=""))
  Pi_mead_all[,,seedN]=MEAD_res$p_hat
  sd_all0[,,seedN]=MEAD_res$p_hat_se
}

cp_mead=NULL
for(j in 1:500){
  int_lower=Pi_mead_all[,j,]-qnorm(alpha)*sd_all0[,j,]
  int_upper=Pi_mead_all[,j,]+qnorm(alpha)*sd_all0[,j,]

  tab1=sapply(1:3,function(k){
    sum(sapply(1:100,function(i) sum(Pi[k,j]<int_upper[k,i] & Pi[k,j]>int_lower[k,i]) ))/100
  })


  cp_mead=rbind(cp_mead,tab1)
}
apply(cp_mead,2,median)
#save(cp_mead,file="output/check_MEAD/cp_mead.RData")

colnames(cp_mead)=c("Cell 1","Cell 2","Cell 3")
vioplot(cp_mead,col=c("grey","lightcoral","skyblue"),ylim=c(0.6,1))
lines(c(0.5,3.5),c(0.95,0.95),lty=2)
```

