---
title: "Linux Command"
author: "Dongyue Xie"
date: "2019-12-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

`cd $SCRATCH`

`htop`: check login mode cpu use

Get compute node:

`sinteractive --time=10:00:00 --mem=8G -c 4 -p mstephens --account=pi-mstephens`

`--exclusive`: 

`squeue -u dyxie` : see job status

`squeue -p mstephens`: see who's using nodes.

`scontrol show node=midway2-0437`

`squeue -p broadwl | less -S`

`export OPENLABS_NUM_THREADS=4`: use 4 cpus to compute 


Open another command window, login to midway2 then `ssh midway2-0437`, `htop --user=dyxie` monitor the computations on the other command window.

Use `screen` to back up screens. 

`nano myscript.R` to write an R script. 

`module load R` then `Rscript myscript.R`


`sbatch myscript.sbatch` 

[parallel in linux command](https://www.msi.umn.edu/support/faq/how-can-i-use-gnu-parallel-run-lot-commands-parallel)

## Unzip (Open) Gz File

`gzip -d file.gz` or `gunzip file.gz`

## Preview files

`head`, `less`

## Upload data to rcc

transfer from my laptop to my home directory:

Single files: `scp <some file> <CNetID>@midway2.rcc.uchicago.edu`

Directories:  `scp -r <some dir> <CNetID>@midway2.rcc.uchicago.edu`

To other directory:

`scp -r <some dir> <CNetID>@midway2.rcc.uchicago.edu:/project2`
