---
title: "RUV"
author: "Dongyue Xie"
date: "2020-01-06"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Assume true relationship, $Y = XB + Z\Gamma + E$, $Z$ is unobserved and can be high correlated with $X$. Goal: find a good surrogate of $Z$, split the effects of $X$ and $Z$ on $Y$. 

Methods: 

1. Remove top PCs of $Y$(Price et al. (2006)). Need $Z\Gamma$ dominates $XB$, otherwise removes effects of $X$.

2. Remove top PCs of $Y-X\hat B$. But confounder effects $Z\Gamma$ are also removed.

3. SVA. The idea is to find a subset of [negative control] genes that are associated with Z but not with X. Weighted SVD with gene weight $p(B_i=0,\Gamma_i\neq 0|Y,X,\hat Z)$.

4. RUV-4. Need to know genes $B_i=0$

5. LEAPP. Assume $B$ is sparse and $Z = X\alpha + W$. Assume we have one variable of interest $B=\beta^T$, then model is $$Y = X(\beta+\Gamma\alpha)^T+(W\Gamma+E)$$



QR decompositon of $X$ is $X=QR$, where $R=(||x||_2,0,0,...,0)^T$. Then $$Q^TY = R\beta^T+Q^TZ\Gamma^T+Q^TE$$.

Then the second to the last row of $Q^TY$ follows $N(0,\Gamma\Gamma^T+E)$.




Open problems:
1. In addition to multiple testing, the surrogate variable analysis
framework can solve many other high-dimensional problems, e.g.,
classification
2. Beyond linear models: High-dimensional random effects model;
GLM; Varying coefficients model; Tree-based methods...
3. Beyond PCA

## Details of irw-sva(Leek and Storey, 2008, PNAS)

$X_{m\times n} = B_{m\times d}S_{d\times n}+\Gamma_{m\times r} G_{r\times n} + U_{m\times n}$

$X$ is $m\times n$, where $m$ indexes features and $n$ is the sample size. The $i$th row of $X$ is $\mathbf{x}_i$.

Primary variables $S$ is of dimension $d\times n$. $\Gamma$ and $G$ have rank $r$.

Algorithm: `irwsva.build` function in sva package.

Let $S_0$ denote null model variables. (In code, mod is parimary variable matrix and mod0 is null)

1. Fit model $X=BS+E$ using ols and obtain $R=X-B\hat S$. Code: `resid <- dat %*% (Id - mod %*% solve(t(mod) %*% mod) %*% t(mod))`.
2. Perform svd on R and obtain right eigenvectors v. Code: `uu <- eigen(t(resid) %*% resid)`, `vv <- uu$vectors`
3. Initialize feature weights `pprob <- rep(1, m)`, set number of sv, `n.sv`, and surrogate variable matrix $G$.
4. Iterate $b=1:B$: 
a. Calculate weights of each feature: (1).  Code: `ptmp <- f.pvalue(dat, mod.b, mod0.b)`, `pprob.b <- (1 - edge.lfdr(ptmp))`, `ptmp <- f.pvalue(dat, mod.gam, mod0.gam)`, `pprob.gam <- (1 - edge.lfdr(ptmp))`. The function `f.pvalue` calculates f-statistics comparing nested models. 
b. Update $G$ with updated weights.






